### ISSUE TITLE
S3 backend example does not support tf_remote_state

### ISSUE THREAD

**Issue by lenni108** [iits-consulting/otc-terraform-template#4]
Dear Dev-Team,

I used your example code and setup the backend as described. The only functionality I am missing is the tf_remote_state. When I try to access this property I am prompted to enter a region. It seems like the prompt only accepts AWS regions but as I am using OTC this also leads to an error.

Is there a way to still us you S3 backend and tf_remote_state or do I have to use a different kind of backend?

Best regards,
Lenny

**Comment by victorgetz** [comment]
Hi AWS regions are not accepted. What is meant is the OTC region like eu-de or eu-nl

Most probably you use not the latest version. otc-auth needs since release 2.0.0 the region for the api endpoints.

Try setting these environment variables:

export TF_VAR_region="eu-de"
export REGION=$TF_VAR_region

**Comment by victorgetz** [comment]
Did you solve your problem?
